### ISSUE TITLE
Fails at npx cdk deploy

### ISSUE THREAD

**Issue by brucegl** [hill-daniel/iot-cdk-stack-setup#8]
Thanks for the blog at https://blog.codecentric.de/en/2020/07/processing-protobufs-with-iot-core/

I am following your instructions. I did npm install, npm run build, npx cdk bootstrap (with my account and region) and npm cdk synth. All these worked fine (I ignored the warnings for now).

However, npx cdk deploy failed with this message: 

IotProtobufCdkSetupStack failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
    at Object.addMetadataAssetsToManifest (/home/me/iot-cdk-stack-setup/node_modules/aws-cdk/lib/assets.ts:28:11)
    at Object.deployStack (/home/me/iot-cdk-stack-setup/node_modules/aws-cdk/lib/api/deploy-stack.ts:177:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/me/iot-cdk-stack-setup/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/home/me/iot-cdk-stack-setup/node_modules/aws-cdk/bin/cdk.ts:235:16)
    at initCommandLine (/home/me/iot-cdk-stack-setup/node_modules/aws-cdk/bin/cdk.ts:169:9)
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")

I'm not sure why my AWS environment (account and region) were not correctly retrieved. I set CDK_DEFAULT_ACCOUNT and CDK_DEFAULT_REGION in my env variables. npx cdk doctor shows the correct CDK env variables (though only the AWS_SDK_LOAD_CONFIG  AWS env variables), however, .../cdk.out/manifest.json is showing unknown/unknown. 

I've also tried with no luck:
$ CDK_DEFAULT_ACCOUNT=123456789012 \
 CDK_DEFAULT_REGION=eu-west-2 \
 npx cdk deploy

Any thoughts would be appreciated.

**Comment by brucegl** [comment]
Oh, I literally needed to run "cdk bootstrap aws://unknown-account/unknown-region", without my account or region. This works I think. I will continue with your instructions :-)
UPDATE: Ah-ha - using unknown-account/unknown-region is (currently) creating stacks in North Virginia. That's OK but, is it possible to change region? I'll see if something like unknown-account/eu-west-2 works.

**Comment by brucegl** [comment]
Daniel provided the fix for me. I needed to add the following in ~/.aws/config:
[default]
region=eu-west-2
output=json
